spring:
  cloud:
    gateway:
      routes:
        - id: website-service
          uri: http://localhost:8081
          predicates:
            - Path=/article/**, /tag/**, /type/**, /BannerImage/**,/Image/**
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: mail-service
          uri: http://localhost:8083
          predicates:
            - Path=/mail/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

  auth:
    service:
      uri: http://localhost:8082